Fixed sidebar use
mprins/dokuwiki-plugin-backlinks pull request #19
Opened 2017-08-08 12:49 UTC by igittigitt

Add some fixes to use this plugin inside a sidebar (regardless which one, the plugin detects for itself).
Also remove some unneccessary code form syntax.php.

2017-08-08 13:47 UTC, mprins requested changes

2017-08-08 13:47 UTC, mprins commented on syntax.php
> +if (!defined('DOKU_INC')) die();
if should use brackets

2017-08-08 13:47 UTC, mprins commented on syntax.php
> +	    }
moving this here makes the check specific to xhtml mode and not any others like it did before

2017-08-08 13:47 UTC, mprins commented on syntax.php
> +            dbglog($backlinks, "backlinks: all backlinks to: $page_id");
why? $page_id is defined and initialized above and makes sure anyone can understand without need to check what is in data and what it means

2017-08-14 09:47 UTC, igittigitt commented on syntax.php
> +if (!defined('DOKU_INC')) die();
Though i would agree with you, this line was taken from official syntax-template skeleton. So it should be fine to have it like all other plugins.

2017-08-14 10:05 UTC, igittigitt commented on syntax.php
> +	    }
Well, this was some kind of hack. My goal was to make the plugin useable inside a sidebar-page.
Therefore the "current page" symbol "." in context of sidebar-page shoud resolve to the displayed wikipage displayed at runtime. Therefore it should not be cached. So i looked for a way to transport this information to the rendering function and used the dot. Maybe we should extend syntax here for usage in sidebar?

2017-08-14 10:06 UTC, igittigitt commented on syntax.php
> +            dbglog($backlinks, "backlinks: all backlinks to: $page_id");
Yeah, this could be removed here.

2017-09-07 09:00 UTC, mprins commented
Closing this as:
-  non of the requested review notes were addressed, 
- does not provide a test case testing the new code 
- and (even after merging in master) causes test failures of existing test cases

2017-09-07 09:00 UTC, closed without merging